// one typed vocabulary for every rejection in the pipeline. relay exposes ~70 failReason codes on
// /intents/status/v3; these are the same classes, named the same way where they overlap.
export const FailureReason = {
    NO_ROUTES: "NO_ROUTES",
    UNSUPPORTED_CHAIN: "UNSUPPORTED_CHAIN",
    GAS_EXCEEDS_OUTPUT: "GAS_EXCEEDS_OUTPUT",
    NEGATIVE_AMOUNT_AFTER_FEES: "NEGATIVE_AMOUNT_AFTER_FEES",
    BELOW_MINIMUM_OUTPUT: "BELOW_MINIMUM_OUTPUT",
    UNPROFITABLE: "UNPROFITABLE",
    SOLVER_BALANCE_TOO_LOW: "SOLVER_BALANCE_TOO_LOW",
    SLIPPAGE: "SLIPPAGE",
    EXECUTION_REVERTED: "EXECUTION_REVERTED",
    SWAP_USES_TOO_MUCH_GAS: "SWAP_USES_TOO_MUCH_GAS",
    ORDER_EXPIRED: "ORDER_EXPIRED",
    QUOTE_NOT_FOUND: "QUOTE_NOT_FOUND",
    ORDER_ALREADY_FILLED: "ORDER_ALREADY_FILLED",
    DEPOSIT_CONFIRMATION_TIMEOUT: "DEPOSIT_CONFIRMATION_TIMEOUT",
    DEPOSIT_REORGED: "DEPOSIT_REORGED",
    SETTLEMENT_REJECTED: "SETTLEMENT_REJECTED",
    REFUND_REJECTED: "REFUND_REJECTED",
    PAYOUT_FAILED: "PAYOUT_FAILED",
    INTERRUPTED: "INTERRUPTED",
} as const;

export type FailureReason = (typeof FailureReason)[keyof typeof FailureReason];
